name: Docker CD Pipeline

on:
  workflow_run:
    workflows: ["Docker CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull fredaluo/aws_docker_cicd:latest

      - name: Delete Old docker container
        run: sudo docker rm -f aws_docker_cicd-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name aws_docker_cicd-container fredaluo/aws_docker_cicd
